name: Free PR Summary with GPT-OSS:22b (No API)

on:
  pull_request:
    types: [opened]

jobs:
  summarize:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR details (diff + files)
        id: pr-data
        run: |
          gh pr checkout ${{ github.event.pull_request.number }} --repo ${{ github.repository }}
          DIFF=$(git diff ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }} | head -c 5000 | sed 's/^/    /')
          FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }} | paste -sd ',' -)
          COMMITS=$(git log --oneline ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }} | head -3 | sed 's/^/    /')
          echo "diff<<EOF" >> $GITHUB_OUTPUT
          echo "$DIFF" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "files=$FILES" >> $GITHUB_OUTPUT
          echo "commits<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMITS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sh
          echo "OLLAMA_MAX_LOADED_MODELS=1" >> $GITHUB_ENV
          ollama serve &
          OLLAMA_PID=$!
          echo "OLLAMA_PID=$OLLAMA_PID" >> $GITHUB_ENV
          sleep 10
          # Verify Ollama is running
          if ! pgrep -x ollama > /dev/null; then
            echo "Error: Ollama failed to start"
            exit 1
          fi

      - name: Pull GPT-OSS:22b (quantized)
        run: |
          echo "Pulling GPT-OSS:22b model (this may take a few minutes)..."
          if ! ollama pull gpt-oss:22b-q4_0; then
            echo "Error: Failed to pull GPT-OSS model"
            exit 1
          fi
          echo "Model pulled successfully:"
          ollama list | grep gpt-oss

      - name: Build prompt for GPT-OSS:22b
        id: prompt
        env:
          TITLE: ${{ github.event.pull_request.title }}
          BODY: ${{ github.event.pull_request.body }}
          AUTHOR: ${{ github.event.pull_request.user.login }}
          DIFF: ${{ steps.pr-data.outputs.diff }}
          FILES: ${{ steps.pr-data.outputs.files }}
          COMMITS: ${{ steps.pr-data.outputs.commits }}
        run: |
          cat > /tmp/prompt.txt <<EOF
          You are an expert PR analysis assistant powered by GPT-OSS:22b. Output **EXACTLY** this format:

          **PR submitted by:** @${AUTHOR}

          **Summary of changes:**
          [2-3 sentence overview. Key files: ${FILES}]

          **Suspected purpose:**
          [Infer intent from code, commits, description]

          **Technical analysis:**
          [Code quality, patterns, tests, architecture]

          **Impact on repository:**
          [Benefits: bugs, perf, security, maintainability]

          Title: ${TITLE}
          Description:
          ${BODY}
          Commits:
          ${COMMITS}
          Diff:
          ${DIFF}
          EOF
          echo "file=/tmp/prompt.txt" >> $GITHUB_OUTPUT

      - name: Generate summary with GPT-OSS:22b
        id: summary
        run: |
          echo "Running GPT-OSS:22b inference (timeout: 5 minutes)..."
          # Run with timeout to prevent hanging
          timeout 300 ollama run gpt-oss:22b-q4_0 < ${{ steps.prompt.outputs.file }} > /tmp/summary_raw.md 2>&1 || {
            EXIT_CODE=$?
            if [ $EXIT_CODE -eq 124 ]; then
              echo "Warning: Model inference timed out after 5 minutes"
            else
              echo "Warning: Model inference failed with exit code $EXIT_CODE"
            fi
          }

          # Clean up Ollama prompt markers and format output
          if [ -f /tmp/summary_raw.md ] && [ -s /tmp/summary_raw.md ]; then
            sed -e '/^>>> /d' -e '/^<<< /d' -e '/^pulling manifest/d' -e '/^verifying sha256/d' /tmp/summary_raw.md > /tmp/summary.md
          fi

          # Fallback if summary is empty or missing
          if [ ! -s /tmp/summary.md ]; then
            cat > /tmp/summary.md <<EOF
          **PR submitted by:** @${{ github.event.pull_request.user.login }}

          **Summary of changes:**
          Analysis failed or timed out. Please review manually.

          **Files changed:** ${{ steps.pr-data.outputs.files }}
          EOF
          fi

          echo "=== Generated Summary ==="
          cat /tmp/summary.md
          echo "content<<EOF" >> $GITHUB_OUTPUT
          cat /tmp/summary.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment on PR
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} \
            --body-file /tmp/summary.md \
            --repo ${{ github.repository }}

      - name: Cleanup
        if: always()
        run: |
          # Clean up temporary files
          rm -f /tmp/prompt.txt /tmp/summary.md /tmp/summary_raw.md
          # Stop Ollama if it's still running
          if [ -n "$OLLAMA_PID" ] && kill -0 $OLLAMA_PID 2>/dev/null; then
            kill $OLLAMA_PID
          fi
