# Audio format
TARGET_SAMPLE_RATE: int = 44100  # Hz
TARGET_CHANNELS: int = 2  # Stereo

# STFT parameters
N_FFT: int = 4096
HOP_LENGTH: int = 1024
WIN_LENGTH: int = N_FFT
WINDOW: str = "hann"
N_FREQ_BINS: int = N_FFT // 2 + 1
STFT_CENTER: bool = False

# Default normalization settings
DEFAULT_WAVEFORM_NORM: str = "peak"
DEFAULT_SPECTROGRAM_NORM: str = "freq_minmax"

# Default stem ordering
STEMS_4: list[str] = ["drums", "bass", "vocals", "other"]

# Progress UI theme (Rich progress bar colors)
BAR_COMPLETE_STYLE: str = "#FF4D6D"
BAR_FINISHED_STYLE: str = "#39FF14"
BAR_PULSE_STYLE: str = "#6E2CA5"
COUNT_STYLE: str = "#B8A9D9"
LOSS_STYLE: str = "#FF8C1A"
FINAL_AVG_LOSS_STYLE: str = "white"
EQ_STYLE: str = "#39FF14"
ELAPSED_STYLE: str = "#FF4D6D"
REMAINING_STYLE: str = "white"

# Precomputed EQ spinner frames (generated by src/eq_frames.py).
EQ_FRAMES: tuple[str, ...] = (
    "█▅▃▄▇",
    "█▅▃▄▆",
    "▇▄▂▃▆",
    "█▅▃▄▇",
    "█▅▃▄▆",
    "▇▄▂▃▆",
    "▁▁▁▁▁",
    "▁▁▁▁▁",
    "▁▁▁▁▁",
    "▁▁▁▃█",
    "▁▁▁▃█",
    "▁▁▁▂▇",
    "▄▄▄▄█",
    "▃▄▆▅▇",
    "▃▄▇▅▆",
    "▁▁▁▁▁",
    "▁▁▁▁▁",
    "▁▁▁▁▁",
    "█▅▃▃▅",
    "█▅▃▃▄",
    "▇▄▂▂▄",
    "▁▁▁▂▆",
    "▁▁▁▂▅",
    "▁▁▁▂▅",
    "█▅▃▄▇",
    "█▅▃▄▆",
    "▇▄▂▃▆",
    "▁▁▁▃█",
    "▁▁▁▃▇",
    "▁▁▁▂▆",
    "▁▁▁▃█",
    "▁▁▁▃█",
    "▁▁▁▂▇",
    "▁▁▁▁▁",
    "▁▁▁▁▁",
    "▁▁▁▁▁",
    "▄▄▄▄▆",
    "▃▄▆▅▅",
    "▃▄▇▅▅",
    "▁▁▁▁▁",
    "▁▁▁▁▁",
    "▁▁▁▁▁",
    "█▅▃▄█",
    "█▅▃▄▇",
    "▇▄▂▃▆",
    "█▅▃▄█",
    "█▅▃▄█",
    "▇▄▂▃▇",
)
