#!/usr/bin/env python3
"""
AI-powered code review script using Anthropic's Claude API.
This script reviews pull request changes and posts feedback as PR comments.
"""

import os
import sys
import json
from anthropic import Anthropic
import requests

def read_file(filepath):
    """Read file contents."""
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            return f.read()
    except Exception as e:
        print(f"Error reading {filepath}: {e}")
        return ""

def get_ai_review(diff_content, changed_files, model="claude-3-5-sonnet-20241022"):
    """Get AI review from Claude API."""
    api_key = os.environ.get('ANTHROPIC_API_KEY')
    
    if not api_key:
        print("ERROR: ANTHROPIC_API_KEY not set. Please add it to repository secrets.")
        print("To get an API key, visit: https://console.anthropic.com/")
        return None
    
    client = Anthropic(api_key=api_key)
    
    prompt = f"""You are an expert code reviewer. Please review the following pull request changes.

Changed Files:
{changed_files}

Diff Content:
{diff_content}

Please provide a thorough code review focusing on:
1. Code quality and best practices
2. Potential bugs or issues
3. Security concerns
4. Performance considerations
5. Readability and maintainability
6. Suggestions for improvement

Format your response as a detailed review with specific line references where applicable.
Be constructive and helpful in your feedback.
"""
    
    try:
        message = client.messages.create(
            model=model,
            max_tokens=4096,
            messages=[
                {"role": "user", "content": prompt}
            ]
        )
        
        return message.content[0].text
    except Exception as e:
        print(f"Error calling Claude API: {e}")
        return None

def post_review_comment(review_text):
    """Post the AI review as a PR comment."""
    github_token = os.environ.get('GITHUB_TOKEN')
    pr_number = os.environ.get('PR_NUMBER')
    repo_name = os.environ.get('REPO_NAME')
    
    if not all([github_token, pr_number, repo_name]):
        print("Missing required environment variables")
        return False
    
    url = f"https://api.github.com/repos/{repo_name}/issues/{pr_number}/comments"
    
    headers = {
        'Authorization': f'token {github_token}',
        'Accept': 'application/vnd.github.v3+json'
    }
    
    comment_body = f"""## 🤖 AI Code Review (Claude)

{review_text}

---
*This review was generated by Claude AI. Please use your judgment when addressing these suggestions.*
"""
    
    data = {
        'body': comment_body
    }
    
    try:
        response = requests.post(url, headers=headers, json=data)
        response.raise_for_status()
        print(f"Successfully posted AI review comment to PR #{pr_number}")
        return True
    except Exception as e:
        print(f"Error posting comment: {e}")
        return False

def main():
    """Main function to run AI code review."""
    print("Starting AI code review...")
    
    # Read PR diff and changed files
    diff_content = read_file('pr_diff.txt')
    changed_files = read_file('changed_files.txt')
    
    if not diff_content:
        print("No changes detected in PR diff")
        sys.exit(0)
    
    print(f"Analyzing {len(diff_content)} characters of diff content...")
    
    # Get AI review
    review = get_ai_review(diff_content, changed_files)
    
    if not review:
        print("Failed to get AI review")
        sys.exit(1)
    
    # Save review to file
    with open('review_output.txt', 'w', encoding='utf-8') as f:
        f.write(review)
    
    print("\nAI Review Summary:")
    print("=" * 80)
    print(review[:500] + "..." if len(review) > 500 else review)
    print("=" * 80)
    
    # Post review as PR comment
    if post_review_comment(review):
        print("AI review completed successfully!")
    else:
        print("AI review generated but failed to post as comment")
        sys.exit(1)

if __name__ == "__main__":
    main()
