#!/usr/bin/env python3
"""
AI-powered code review script using xAI's Grok API.
This script reviews pull request changes and posts feedback as PR comments.
Grok offers free tier access making it cost-effective for open source projects.
"""

import os
import sys
import json
from openai import OpenAI
import requests

# Configuration constants
REVIEW_PREVIEW_LENGTH = 500  # Number of characters to show in console preview

def read_file(filepath):
    """Read file contents."""
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            return f.read()
    except Exception as e:
        print(f"Error reading {filepath}: {e}")
        return ""

def get_ai_review(diff_content, changed_files, model="grok-beta"):
    """Get AI review from xAI Grok API."""
    api_key = os.environ.get('XAI_API_KEY')
    
    if not api_key:
        print("ERROR: XAI_API_KEY not set. Please add it to repository secrets.")
        print("To get a FREE API key, visit: https://console.x.ai/")
        return None
    
    # xAI uses OpenAI-compatible API
    client = OpenAI(
        api_key=api_key,
        base_url="https://api.x.ai/v1"
    )
    
    prompt = f"""You are an expert code reviewer. Please review the following pull request changes.

Changed Files:
{changed_files}

Diff Content:
{diff_content}

Please provide a thorough code review focusing on:
1. Code quality and best practices
2. Potential bugs or issues
3. Security concerns
4. Performance considerations
5. Readability and maintainability
6. Suggestions for improvement

Format your response as a detailed review with specific line references where applicable.
Be constructive and helpful in your feedback.
"""
    
    try:
        completion = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": "You are an expert code reviewer providing constructive feedback."},
                {"role": "user", "content": prompt}
            ],
            max_tokens=4096,
            temperature=0.7
        )
        
        return completion.choices[0].message.content
    except Exception as e:
        print(f"Error calling xAI Grok API: {e}")
        return None

def post_review_comment(review_text):
    """Post the AI review as a PR comment."""
    github_token = os.environ.get('GITHUB_TOKEN')
    pr_number = os.environ.get('PR_NUMBER')
    repo_name = os.environ.get('REPO_NAME')
    
    if not all([github_token, pr_number, repo_name]):
        print("Missing required environment variables")
        return False
    
    url = f"https://api.github.com/repos/{repo_name}/issues/{pr_number}/comments"
    
    headers = {
        'Authorization': f'token {github_token}',
        'Accept': 'application/vnd.github.v3+json'
    }
    
    comment_body = f"""## 🤖 AI Code Review (Grok)

{review_text}

---
*This review was generated by xAI's Grok AI (FREE tier). Please use your judgment when addressing these suggestions.*
"""
    
    data = {
        'body': comment_body
    }
    
    try:
        response = requests.post(url, headers=headers, json=data)
        response.raise_for_status()
        print(f"Successfully posted AI review comment to PR #{pr_number}")
        return True
    except Exception as e:
        print(f"Error posting comment: {e}")
        return False

def main():
    """Main function to run AI code review."""
    print("Starting AI code review...")
    
    # Read PR diff and changed files
    diff_content = read_file('pr_diff.txt')
    changed_files = read_file('changed_files.txt')
    
    if not diff_content:
        print("No changes detected in PR diff")
        sys.exit(0)
    
    print(f"Analyzing {len(diff_content)} characters of diff content...")
    
    # Get AI review
    review = get_ai_review(diff_content, changed_files)
    
    if not review:
        print("Failed to get AI review")
        sys.exit(1)
    
    # Save review to file
    with open('review_output.txt', 'w', encoding='utf-8') as f:
        f.write(review)
    
    print("\nAI Review Summary:")
    print("=" * 80)
    print(review[:REVIEW_PREVIEW_LENGTH] + "..." if len(review) > REVIEW_PREVIEW_LENGTH else review)
    print("=" * 80)
    
    # Post review as PR comment
    if post_review_comment(review):
        print("AI review completed successfully!")
    else:
        print("AI review generated but failed to post as comment")
        sys.exit(1)

if __name__ == "__main__":
    main()
